
FROM golang:1.25-alpine AS builder

WORKDIR /app


COPY go.mod go.sum ./
RUN go mod download


COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -o /bin/control-plane ./cmd/control-plane


FROM gcr.io/distroless/static-debian12

COPY --from=builder /bin/control-plane /control-plane


EXPOSE 8080

ENTRYPOINT ["/control-plane"]
