apiVersion: v1
kind: Service
metadata:
  name: {{ include "autopilot.fullname" . }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autopilot.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controlPlane.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "autopilot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
