apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inference-autopilot-reader-binding
subjects:
  - kind: ServiceAccount
    name: inference-autopilot
    namespace: inference-autopilot
roleRef:
  kind: ClusterRole
  name: inference-autopilot-reader
  apiGroup: rbac.authorization.k8s.io